### ISSUE TITLE
No config pop-up and no auto dashboard

### ISSUE THREAD

**Issue by hatch01** [lfpoulain/ha-eco2mix#5]
Hi,
I installed eco2mix using hacs on my HA 2024.12.2.
I got all the data added correctly to home assistant.
However, I was not asked to configure it with this popup 
![image](https://github.com/user-attachments/assets/dc976251-7ac3-42aa-a491-76b789cdd2f6)
And can't find a way to get this config page.
I also don't get the energy dashboard created automatically.
I checked my logs and found no error related to eco2mix

Thanks

**Comment by lfpoulain** [comment]
Hi,

Thank you for reaching out.

The configuration popup to add sensors is no longer available (the README has been updated accordingly). You can activate the sensors through the Entities page of the integration in Home Assistant.

As for the Energy Dashboard, it needs to be added manually following the usual procedure for dashboard in Home Assistant.

**Comment by hatch01** [comment]
Thank you for your prompt answer! 
I still not understand how I am supposed to add the dashboard you made.
I copied and past the dashboard yaml config I found in the repo and made some little tweaks on the sensor's name to make it work.
Is it how I was supposed to do?

<details>
<summary>My dashboard config</summary>

```yaml
views:
  - title: éCO2mix
    path: eco2mix
    icon: mdi:flash
    cards:
      - type: grid
        columns: 3
        square: false
        cards:
          - type: entity
            name: Consommation
            entity: sensor.eco2mix_consommation
            icon: mdi:flash
          - type: entity
            name: Production
            entity: sensor.eco2mix_production_totale
            icon: mdi:lightning-bolt
          - type: entity
            name: Export
            entity: sensor.eco2mix_exportation
            icon: mdi:export
      - type: custom:apexcharts-card
        header:
          title: Production et Consommation
          show: true
        graph_span: 24h
        series:
          - entity: sensor.eco2mix_consommation
            name: Consommation
            type: line
            stroke_width: 2
            color: '#e74c3c'
          - entity: sensor.eco2mix_production_totale
            name: Production
            type: line
            stroke_width: 2
            color: '#2ecc71'
      - type: custom:pie-chart-card
        title: Répartition de la Production
        entities:
          - entity: sensor.eco2mix_pourcentage_nucleaire
            name: Nucléaire
            color: '#3498db'
          - entity: sensor.eco2mix_pourcentage_eolien
            name: Éolien
            color: '#27ae60'
          - entity: sensor.eco2mix_pourcentage_solaire
            name: Solaire
            color: '#f1c40f'
          - entity: sensor.eco2mix_pourcentage_hydraulique
            name: Hydraulique
            color: '#3498db'
          - entity: sensor.eco2mix_pourcentage_bioenergies
            name: Bioénergies
            color: '#2ecc71'
          - entity: sensor.eco2mix_pourcentage_gaz
            name: Gaz
            color: '#e67e22'
          - entity: sensor.eco2mix_pourcentage_charbon
            name: Charbon
            color: '#7f8c8d'
          - entity: sensor.eco2mix_pourcentage_fioul
            name: Fioul
            color: '#95a5a6'
        animation: true
        card_height: 400
```
</details>
